lunduniversity/introprog

- compendium/modules/w01-exercise.tex
Fixed every typo that I could find in the first exercise. 
I am not sure whether the added `\code{}` blocks are classed as typos, but it seemed better to keep the style consistent.
Any comments and feedback would be appreciated!
(`sbt pdf` asserts success!)
> fix typos in exercise w01

- compendium/modules/w06-lab.tex
The specification for Point no longer leaves out the type of the x,y parameters. Instead, the type is given upfront and the reasoning behind the choice is explained.
> Update turtlegraphics Point specification.

- compendium/modules/w06-solutions.tex
The current methods `def x` and `def y` are not correct setters (they are normal methods). They are missing: `_=` which identifies them as setters.
> Added "_=" to identify the methods as a setter in Exercise 6.11e

- workspace/w09_maze/src/main/scala/maze/AMazeIngRace.scala
I could not run the maze lab on {linux, windows} + IntelliJ (with sbt plugin) due to the use of `new File(".")` which in IntelliJ yields the root project (workspace/) rather than the submodule (w09_maze).
Normally, we could get around this by not explicitly relying on a directory path, but just using `getResource(filename)` to access the maze files. However, since the lab is explicitly teaching file handling rather than resource use, I instead fixed the problem by dynamically getting the directory where the resources are stored.
Tested and working on following platforms:
linux + sbt
linux + IntelliJ IDEA (with sbt plugin)
windows + IntelliJ IDEA (with sbt plugin)
What do you think? Is it confusing to the students to use a path which is somewhere in the target/ directory?
> fix maze path being dependent on CWD; use resource dir

- workspace/w10_survey2/src/main/scala/stats/Command.scala
- workspace/w10_survey2/src/main/scala/stats/Main.scala
- workspace/w10_survey2/src/main/scala/stats/Table.scala
- The code for getting the resource directory is now only in one place instead of three.
- The same fix as in 45ec99f is applied, making special characters work in paths. (Writing paths with spaces during the command loop is impossible for command parsing reasons, but spaces do work in paths provided as arguments to main.)
- Instead of having hardcoded checks for strings starting with "http", the program now determines if something is a URL by trying to create a URL object from it. If there is no valid protocol, a MalformedURLException is thrown, which we catch.
- Path.resolve is now used instead of string concatenation, which lets the user optionally enter absolute paths.
I don't have access to many testing environments here, but it seems to work fine in at least Windows+IntelliJ.
Is it …
> survey2: Improve path handling

- compendium/modules/w13-assignment-bank.tex
As pointed out by the students, there were some inconsistencies in the compendium about which classes were required. 
Main changes:
* All mentions of Transaction have now been updated to refer to BankEvent (which was originally renamed since some of the events are not strictly transactions).
* Fixed mentions of singleton objects that were being referred to as classes.
> Fix inconsistencies in bank

- compendium/modules/w13-assignment-bank.tex
There were a number of errors and inconsistencies in the example output for bank, including:
* Some outputs were being matched with the wrong user action (notably 3 and 7 being switched around). 
* ID numbers for the customers in the examples were not consistent throughout the examples
* The outputs for user action 2 (find customers by name) were inconsistent. Some showed listed accounts and others listed customers only. Since the specification has a `findByName` method (returning Customers) and it is only used for this purpose, I changed all of the examples to only list the customers and not their accounts.
I also changed the example output for 8 (restoring to old state) to be usable as a test case for the log file provided in the workspace.
TLDR: Examples fixed. Action 2 should return …
> Fix example output in bank

- compendium/modules/w12-lab.tex
lthopoly uses money and move spaces, not risk and chance spaces.
> lthopoly: Make game board printout in instructions accurate

- compendium/modules/w11-exercise.tex
The original text was ambiguous (are comparisons done by code point or code value?). This commit adds a footnote so that those who want to find out more can get an accurate definition of comparison in Scala/Java. The idea of the footnote is to point out that supplementary characters exist and may need to be handled in a special way, while not going into the details of how supplementary characters are encoded. The linked Wikipedia page describes the details (and also explains a little about Unicode and its history, unlike the equivalent page on Swedish Wikipedia).
> Add expanded footnote about comparison and Unicode

- contributors.tex
The author list hyphenated Palmqvist as Pal-mqvist instead of the correct Palm-qvist. This commit fixes that, and also fixes missing and incorrect hyphenations that currently aren't used but might be used if the layout is altered.
> Add hyphenation hints for last names of authors

- compendium/modules/w13-exercise.tex
W3Schools is not often regarded as a good resource, so I'm replacing the links to it with a link to the more respected MDN (Mozilla Development Network).
> Replace W3Schools links

- README.md
Hi everyone,
I noticed that the link to PDF version of compendium is not working and I updated it.
Basically, the link I added is something we call "Build URL" - each time it's visited, [latexonline.cc](https://latexonline.cc) will fetch all TeX files from the repository (if they were updated) and create the PDF. You won’t need to re-generate PDF each time its sources are updated. And if there are no updates, the service will return cached version.
We recently updated latexonline.cc to be more convenient for the users and I thought your repository is a good example where the service will be useful.
Let me know what you think.
> Added "Build URL" for compendium

- compendium/modules/w01-intro-exercise.tex
The way that the compendium is worded right now, it's asking for the amount of grains in the 64th square, but both the answer (2^64 - 1) and the Wikipedia article are about the total amount of grains.
@bjornregnell This is the problem that I mentioned very briefly earlier today.
> Fix chapter 1 task 6 (chessboard grains)

- compendium/prechapters/course-instructions.tex
Fixing the link for the study-group contract example, so it works correctly.
> Course Instructions - Fixing link

- compendium/modules/w06-sequences-exercise.tex
That Swedish letters don't sort as expected is not just because of historical reasons – it is impossible to have one sorting order that's correct for all languages, so even if we were to make a new order, it'll be wrong for some amount of languages no matter what. As an example, Ö is the last letter of the alphabet in Swedish, but German places it earlier in the alphabet, so making the order correct for Swedish would make it wrong for German.
(Of course, it's possible to write programs that select different sorting orders depending on e.g. a language setting, but this part of the compendium is about the "built-in" order that Char has.)
> Reword w06 footnote about Swedish sorting

- quiz/Main.scala
- quiz/QuizData.scala
- quiz/TypesAndUtils.scala
This prevents all the existing quizzes from being re-shuffled every time the quizzes are rebuilt, which should make the future commit history cleaner.
By default, the seed used for shuffling is a hash of the name of the quiz, but it's also possible to specify a seed manually.
> Use hash of quiz name as seed for shuffling

- compendium/modules/w01-intro-lab.tex
The method `randomWalk(n: Int, step: Int, angle: Int)` could confuse the student because of the variables `step` and `angle` that could be re-used by the student in the method.
Instead i recommend `maxStep` and `maxAngle` as params for `randomWalk`-method to eliminate the confusion.
> Change of unclear params in randomWalk

- workspace/w06_shuffle/src/main/scala/cards/TestDeck.scala
TestDeck.testShuffle() contained a small bug whereby biased (but complete) shuffles would show as even
> Fixed subtle bug in testShuffle()

- compendium/modules/w13-assignment-bank.tex
There are only two reasonable ways to implement these two methods, and neither is good design:
1. Both methods create a BankEvent and call doEvent. This would be reasonable behavior, but then why are there such methods for creating/removing accounts but not for depositing/withdrawing/transferring money?
2. Both methods modify the state directly without creating a BankEvent. In this case, the methods must not be called by anything other than doEvent, so they should not be public.
> bank: Remove addAccount and removeAccount from spec

- compendium/modules/w13-assignment-bank.tex
The old way of doing it only prevented column breaks between lines, not column breaks in the middle of lines.
> Prevent column breaks in bank examples in a more robust way

- compendium/modules/w13-assignment-bank.tex
- workspace/w13_bank_proj/src/main/scala/bank/time/Date.scala
This change improves the "natural format" of Dates:
- Hours and minutes have leading zeroes
- Seconds aren't shown since they always are stored as 0
- Extra spaces are removed
- "CET" is removed - it was hardcoded rather than providing actual info
The formatting code is also made a bit neater.
> bank: Improve date formatting

- compendium/modules/w09-inheritance-exercise.tex
This is the same problem as the bank project had last year: 32-bit integers are a bit too small for storing 10-digit numbers.
> Store personnummer as Long in w09

- compendium/modules/w10-patterns-lab.tex
The majority of modern computers do not have sound cards that include hardware synthesizers. That was only really popular during the 90s. For the reference, Microsoft added a software synthesizer in Windows 98 and removed support for hardware synthesizers in Windows Vista.
> Correct facts about MIDI synthesizers

- compendium/modules/w10-patterns-exercise.tex
Eftersom medlemmarna re och im är privata fungerar inte den föreslagna lösningen i punkt 6. kompilatorn ger felmeddelandet " error: value im is not a member of Complex". Om man däremot gör medlemmarna publika eller kör en case class istället för en vanlig class så försvinner problemet
override def equals(other: Any): Boolean = {
other match{
case that: Complex => (that canEqual this) && (that.re == this.re) && (that.im == this.im)
case _ => false
}
}
> Edit w10 Excersice 19

- workspace/w10_music/src/main/scala/music/Synth.scala
Changed first default instrument from grand to piano to reflect instrument names on Windows. The program will still find grand piano on Mac and Linux. 
Added if statement on line 30. In case no instruments are found fall back to piano.
This change has been tested on my Windows computer, a Mac and the Linux computers in the basement of the E building.
> Update Synth.scala in lab w10_music 

- workspace/w10_music/src/main/scala/music/Synth.scala
Neither "grand" nor "guit" is found on Windows 10 (maybe other versions of Windows as well). The grand piano is probably one of the instruments containing "piano" and the guitars contains "gt".
Because there might be a system where the instrument is called something different, it is impossible to completely fix this issue, so that it will always play the correct sound by default on every channel on every system with the current implementation of Synth.resetInstruments().
What the code does is just ignoring the instruments (in Synth.defaultInstruments) that it cannot find, which means that the default sound (piano probably) will be played on those channels instead. This means that this fix is allowing you to complete the lab, but with the wrong sounds (channel 1 is piano sound instead of …
> Update Synth.scala music lab

- workspace/w10_music/src/main/scala/music/Synth.scala
Different implementations of MIDI synths don't necessarily use the same names for instruments, so relying on names our code fragile. We can however rely on the program numbers being the same everywhere, since those are specified by the General MIDI standard.
I included constants for all 128 programs, which might be a bit overkill, but maybe someone wants to play around with playing chords using gunshots or crystals... :)
The fallback added by PR #333 is still included. If no matching instrument is found, the instrument remains unchanged.
> w10_music: Select instruments by program rather than name

- compendium/modules/w13-assignment-bank.tex
The menu choice for printing the history was missing from the example printout, and task 6 wrongly said to implement choice 9 instead of choice 10.
To clarify, the intent was to implement history printing in task 4b) and to implement history rollback in task 6.
> bank: Fix missing menu choice and wrongly numbered menu choice

- compendium/modules/w07-setmap-exercise.tex
Trailing commas are supported in the version of Scala that we're using, so this task doesn't make sense anymore. Fixes #300.
> Remove trailing comma exercise

- plan/Plan.scala
- slides/body/lect-w13-exam-tips.tex
There are still some references left in lectures and the imageprocessing lab, but those can be dealt with later.
> Replace references to SimpleWindow with PixelWindow

- compendium/modules/w05-classes-exercise.tex
Use more consistent spacing in Exercise 5's `def move.`
Don't refer to Mole as a case-class when it has no case prefix in the example/template code.
> Consistency fixes in chapter 5's exercises

- workspace/w06_shuffle/src/main/scala/cards/TestDeck.scala
Now says 16.66666% instead of 0.16666%.
> Fixed percentages

- slides/body/lect-w07-collections.tex
Corrects a small typo in the lecture slides for week 7 (collections).
> Correct typo in w07 lecture slides

- compendium/modules/w07-setmap-lab.tex
In [Lab 7 exercise 4](https://github.com/lunduniversity/introprog/blob/master/compendium/modules/w07-setmap-lab.tex#L102-L111), the [first step](https://github.com/lunduniversity/introprog/blob/master/compendium/modules/w07-setmap-lab.tex#L105) - to replace any `whitespace` characters with a space (`' '`) - is made redundant by the [second step](https://github.com/lunduniversity/introprog/blob/master/compendium/modules/w07-setmap-lab.tex#L106) - to replace any non-letter characters with a space (`' '`).
The reasoning behind this is that there are, as far as I understand, no (16-bit) characters that pass the test of being both a whitespace- and letter-character. All whitespace characters are "non-letter characters". 
```scala
scala> (Char.MinValue to Char.MaxValue).find(c => …
```
> Remove redundant step from Lab 7 Exercise 4 instructions 

- contributors.tex
Feels a bit lite patting my own shoulder, but... It's fun. Thanks for the offer @bjornregnell :smile: 
Thought: Would be pretty cool to generate this from the [contributors page](https://github.com/lunduniversity/introprog/graphs/contributors) with [GitHub's API](https://developer.github.com/v3/repos/#list-contributors) :) Either with Travis, or with GitHub's new Actions :thinking: 
**But** that could also lead to people getting their name in the book without them wanting to... Maybe not worth overengineering it
> Add myself to the contributors list

- compendium/modules/w08-matrices-exercise.tex
Fix a small formatting bug causing the last bit of a code-block not to use a monospaced font. 
So instead of:
It looked like:
---
Let's be honest, this is just silly procastination from my side.
> Formatting: premature closing of code block

- compendium/modules/w11-scalajava-exercise.tex
A small typo/misreference in the exercise instructions of week 11. The instructions refer to a `findAll` method, which is probably meant to be `foundAll` :man_shrugging:
> Typo in w11 exercise instructions

- compendium/examples/scalajava/hangman2.scala
- compendium/modules/w11-scalajava-exercise.tex
Let `download` directly convert the result of the Try-block to an option, forcing the callee to handle the error instead of providing a fallback case (and println) inside the download method.
**Note:** This _does_ introduce an inconsistency with `hangman1.scala` and `Hangman.java`, as these both `println` an error if such occurs. Not sure if that's relevant, I'll let you be the judge @bjornregnell.
Hopefully less confusing to others
- Remove lines with `.recover{...}`
- Handle result with `Option#getOrElse`
- Update module .tex description (_This was the only place I could find that explicitly mentions the previous format, and I tried my best with some grepping of the `compendium/` directory, with words such as `download`, `läckalånga`, and `recover`. Would be great if someone could …
> Avoid use of .recover in scalajava/hangman2 example

- compendium/modules/w05-classes-exercise.tex
Using uppercase key names in the REPL example might lead to some confusion during the blockbattle lab, since PixelWindow uses lowercase key names.
> Use lowercase key names in KeyControl exercise

- compendium/global-constants.tex
Many places still referred to 1.1.3.
Signed-off-by: Jakob Sinclair <sinclair.jakob@mailbox.org>
> Update introprog-scalalib version number to 1.1.4

- slides/body/lect-w06-exceptions.tex
The thirteenth element of xs is at index 12, not 13.
> Fix incorrect indexing in week 6 slides

- compendium/modules/w04-objects-exercise.tex
The text was referring to String-variables in introprog.PixelWindow.Event, which have been refactored to Int-variables (introprog-0.1.1). Also along with this change the REPL-output of introprog.examples.TestPixelWindow changed.
> Fix references to old library code

- slides/body/lect-w11-scalajava.tex
This matches the text under it: "Primitiva arrayer".
An alternative could be: "Primitiv Array"
Signed-off-by: Jakob Sinclair <sinclair.jakob@mailbox.org>
> "Primitiva Array" should be plural

- compendium/modules/w04-objects-lab.tex
Two common mistakes in the blockmole lab are:
1. The `rectangle` function not handling values of `leftTop` other than (0, 0) correctly
2. Pixel coordinates being used where block coordinates were intended
This change gives students finished code to put in `drawWorld`. The code is specifically intended to not work correctly when either of the two mistakes above are present, making the mistakes hard to miss unlike before.
> blockmole: Force correct rectangle drawing

- compendium/modules/w02-programs-exercise.tex
Fix for #475, the missing defintion for r has been added, based on the answer in chapter L.2.3.
> Fix #475 added missing definition for r

- compendium/modules/w04-objects-lab.tex
`keepOnDigging()` should check if `key` is of type `String`, not of type `Char`.
> fix bug in blockmole 11.c

- compendium/modules/w04-objects-lab.tex
fix a typo in the instructions, according to the lab solutions
> fix typo "BlockWindow.keepOnDigging" 

- compendium/modules/w06-patterns-lab.tex
move() is probably not meant to be static, and new Mole.move() should be fixed accordingly.
> fix typo new Mole.move() in lab w06

- compendium/modules/w07-sequences-exercise.tex
In Scala 2.13, calling toArray on an Array does create a new Array.
There are still cases in Scala 2.13 where calling toXXX doesn't create a new collection, but as far as I know this only happens with immutable collections, so the fact that there are cases where no new collection gets created is mostly irrelevant.
> Fix outdated info in answer for exercise 7 task 5

- compendium/modules/w07-sequences-lab-goals.tex
- compendium/modules/w07-sequences-lab.tex
Seems like the actual link got fixed earlier before but not the text...
> Fix workspace link in shuffle instructions

- compendium/postchapters/version-control.tex
In my experience, most people who do not wish to be pseudonymous set git's `user.name` setting to their real name with spaces and diacritics. There is no technical obstacle to doing so, there is no expectation that the name is character-by-character identical to whatever online username you are using, and it looks nicer.
> Use real name instead of username in version control example

- compendium/modules/w07-sequences-exercise.tex
Fixes issue #502 and removes the deprecated uses of prepend and swaps it with prependAll.
> Fix #502 removed deprecated use of prepend in Chapters 7.2.3 and L.7.3

- compendium/examples/AliensOnEarth.scala
- compendium/modules/w03-functions-exercise.tex
- quiz/QuizData.scala
I added some \TODOs in the file:
1. There are two files in compendium/generated/ that I would like to change. Where should I look?
2. "Uppgift 6" is no longer as relevant since the underscore can be omitted in all of the cases described in the exercise. Should I try to change it? Currently, the answers include both the correct answer for Scala 3 and the previous results.
3. "Uppgift 15" uses lastException and :javap which don't seem to be available in the Scala 3 REPL. For now I changed the code and answer to not include them. Since the REPL prints out the stack trace along with the exception I don't think lastException is necessary. Is there another way to show the machine code inside the REPL?
> Migrate exercise w03 functions to Scala 3 fix #542

- compendium/generated/quiz-w07-seq-methods-solurows-generated.tex
- compendium/generated/quiz-w07-seq-methods-taskrows-generated.tex
- compendium/generated/quiz-w07-seq-sort-solurows-generated.tex
- compendium/generated/quiz-w07-seq-sort-taskrows-generated.tex
- compendium/generated/quiz-w07-seq-update-solurows-generated.tex
- compendium/generated/quiz-w07-seq-update-taskrows-generated.tex
- compendium/modules/w07-sequences-exercise.tex
I have now changed all the exercises from week 7 to Scala 3. But I have a few questions/remarks:
1. Exercise 25 is about WrappedArray, but it doesn't seem to exists anymore. Should it be removed completely or something else?
2. Exercise 9, 18, 22, and 27 are all about looking up in Scala doc or "snabbref". That doesn't seem to be updated in Scala 3, but I haven't found any problem using it. I think that I will leave it for now.
> Migrate exercise w07 to Scala 3

- compendium/modules/w05-classes-exercise.tex
- quiz/QuizData.scala
I just discovered that the quizzes in exercise w05 were reset to the version pre-migration, which was due to me incorrectly editing the generated `.tex` files in `compendium/generated` instead of `quiz/QuizData.scala`. This should be fixed in this PR, but I can't build the project as I currently have issues with Scala and sbt, so I haven't been able to check it myself. But according to the Github Actions run it should be fine. I also tried running `sbt build` on another PC that is running Windows, but the build failed there due to Windows missing the program `tail`.
> w05: Fix exercise quizzes and improve solutions

- quickref/quickref.tex
Fixed some typos that I found in quickref. Also changed `call` to be in plural (`recursive call` -> `recursive calls`).
> quickref: Fix typos

- web/tools/tools.md
Scala 3 can now be installed using SDKMAN in Linux/macOS.
> Simplify Scala installation instructions

- slides/body/lect-w02-codestruct.tex
Changing from a print to println to avoid collision status text in sbt since it prints directly on the line. This is also concurrent with function usage in other parts of the code.
> updating example code for clarity

- compendium/modules/w08-matrices-lab.tex
Ändrar _\code{rule}_ till endast _rule_, då jag antar att detta är LaTeX som råkat hamna i Scala-koden
> Tar bort LaTeX-kod från exempelkod

- build.sbt
- compendium/examples/lth-courses/courses.scala
- compendium/modules/w12-extra-exercise.tex
Also bump scala version to `3.1.0`
> w12extra: Remove `:paste` instructions

- quickref/quickref.tex
The descriptions for the mutable set methods add and remove described the wrong behaviour. This PR changes the wording to reflect the real behaviour.
> quickref: Change mutable set method description

- slides/body/lect-w01-intro.tex
As "scala-cli" has "run" as a command, a beginner who has used the command "scala-cli run ." previous to reading this might mistakenly believe that "scala" also has the command "run". However, it doesn’t: "run" only refers to the main function in this example. It would therefore be more pedagogical if the main function was called something different (like "hi").
> Update lect-w01-intro.tex to improve clarity

- slides/body/lect-w05-classes.tex
I noticed the REPL output for Example 5.1.35 didn't match the actual output of running the code.
> fixed example 5.1.35 output

- compendium/modules/w05-classes-exercise.tex
This is a first draft to solve #678. Feedback welcome!
I have not yet managed to compile the compendium to ensure that this looks good.
> in exercises w05, encourage students to try Pos.moved and reflect over results

- compendium/modules/w07-sequences-exercise.tex
- quickref/quickref.tex
Removed && i > 0 in the solution to assignment 7.2.5d as discussed in the discord-server
Since an arrays length can't be shorter than 0 the minimum value for result.length is 1.
if i < result.length then [...] i += 1 guarantees that i is at least equal to 1, so a comparison to see if it's larger than 0 is unnecessary.
The first commit is related to another issue, but I undid the change I made since that issue hasn't been solved yet.
> Removed an unnecessary comparison

- compendium/modules/w01-intro-exercise-goals.tex
- compendium/modules/w01-intro-exercise.tex
- slides/body/lect-w01-intro.tex
- slides/body/lect-w03-functions.tex
- slides/body/lect-w13-on-demand.tex
- slides/simple/intro.tex
`grep "literal" **/*.tex` in root-dir now only shows correct usages.
> fix 717 English literal used in Swedish sentences

- compendium/modules/w02-programs-exercise.tex
Det står motsägande filnamn för sum.sc/sum.scala i W02 övningarna. I instruktionen står det att man bör skapa en fil vid namn "sum.scala" men i exemplet står `code sum.sc`.
Mitt commit redigerar instruktionen till att säga "sum.sc" eftersom det står så senare i texten.
> Korrigering av filnamn av sum.scala till sum.sc

- quiz/QuizData.scala
Det saknas en punkt mellan `xs` och `main` här: (Uppgift 5, W02)
Med tanke på svarsalternativ antar jag punkten bör vara där.
> Punkt tillagd mellan "xs" och "map" i Uppgift 5, W02

- compendium/prechapters/how-to-contribute.tex
- slides/body/lect-w05-classes.tex
I corrected a simple grammatical error:
_Ett objekt som skapats med en klassen ..._ became **Ett objekt som skapats med klassen**.
> fix typo in w05 classes & incorrect contribution URL in how to contribute

- compendium/postchapters/terminal.tex
"Terminalkommando" skulle kunna vara plural ("terminalkommandon") eftersom man oftast använder flera olika terminalkommandon när man programmerar.
> fix typo under appendix b

- compendium/modules/w04-objects-exercise.tex
In the exercise description of exercise 8 in w04 there is a spelling error. "Den tre parametrarna", should be "De tre parametrarna", because "parametrarna" in this case is plural, and not singular.
> Fix spelling error in w04 exercise 8

- compendium/modules/w04-objects-exercise.tex
The solution implies that the problem is a "Yes–no question", however that is not the case (see image below).
> Rephrase solution for exercise w04

- compendium/modules/w04-objects-lab.tex
The "s" is not needed here because string interpolation is not used.
> fix lab code skeleton in w04

- compendium/modules/w06-patterns-exercise.tex
The solution contains one extra empty row (compare the images below). Therefore, beginning at row 12, the solution and the problem does not match.
> Fix solution for exercise w06

- compendium/modules/w01-intro-exercise.tex
- compendium/modules/w01-intro-lab.tex
- compendium/postchapters/kojo.tex
- slides/body/lect-w01-intro.tex
- web/tools/tools.html
- web/tools/tools.md
Sökte igenom hela report efter `kojo.lu.se` och efter `kojo web`. Detta var referenserna jag hittade. Jag har inte kollat hur printen ser ut.
Behöver review och åsikter om huruvida detta skall göras överhuvudtaget.
fix #745
> Remove references to kojo web

- slides/body/lect-wjava-body.tex
Add info about string interning in slide J.1.67 fix #783. Please observe that this fix creates another issue, i.e. overfull vbox for slide J.1.67. Consider addressing this by creating new slide and restructuring text between J.1.67 and J.1.68 and this new slide.
> Add info about string interning in slide J.1.67 fix #783

- compendium/modules/w10-inheritance-exercise.tex
The override modifier is not needed in this case because attributes x and y are not implemented in type Pair.
> Removed override modifer from exercise in W10

- compendium/modules/w04-objects-lab.tex
There is some skeleton code provided during the lab W04 that does not compile because some singleton objects are empty. My change adds the ??? placeholder to fix this and also briefly explains the question mark function.
> Add ??? to skeleton code in lab W04

- compendium/modules/w01-intro-lab.tex
- workspace/w01_kojo/kojo.scala
To generalize `kvadrat` and `stapel` so that the pen and fill color can be specified, one needs to know the type of color variables in Kojo. For students to figure the type out, they either have to study the Kojo source code or use Metals' type derivation. 
I think the type should be specified in this task to minimize confusion.
> update lab task 5f in w01 to clarify type

- compendium/modules/w06-patterns-exercise.tex
fixed a todo in excercise acording to #758. Not certain about what formatting you want on the answer so leave a comment if you like me to change something
> fix todo excercise 6.14

- compendium/modules/w05-classes-exercise.tex
- contributors.tex
"Fine tune" includes fixing all compilation errors in task 5.8 and small tweaks of LaTex. Code is tested and runs fine.
> Close #834 Fine tune exercise 5.8 and add me to contributors

- workspace/w08_life/Life.scala
Removed LaTex code in Scala comment.
> fix life class tips in lab w08

- quickref/quickref.tex
> update index search defs

- slides/body/lect-w01-about.tex
Fortran användes som förstaspråk innan Pascal introducerades. Jag började E 1980 och skrev mitt första program i Fortran på hålkort. Detta år var det sista som hålkort användes. I fortsättningskursen användes Pascal och terminaler.
Jämfört med 1979 var det dock ett framsteg att vi fick köra inläsningen av hålkorten själva. Tidigare fick studenterna lämna in bunten i en reception som sedan läste in hålkorten och körde programmet åt en. Cykeln editera-exekvera-felsöka/förbättra var lite längre så man försökte undvika fel.
> Rätta historisk felaktighet

- web/tools/tools.md
Might be wise to remove Bash stuff since it has no impact on this course?
> Solves https://github.com/lunduniversity/introprog/issues/878
