- compendium/modules/w01-lab.tex
Fixed all typos I could find in this file.
Should I add all recompiled PDF files to commits of this kind now and in the future?
> fix typos in lab w01

- plan/ideas/lab-sketches.md
Added a rough sketch of the shapes lab along with some unanswered questions.
If anyone has thoughts/criticisms to share I'd love to hear them!
> updated lab sketch for the shapes lab

- compendium/modules/w13-assignment-bank.tex
Created the first draft of w13 assignment bank. 
Added description, goals, design and implementation.
> First draft of w13 assignment bank

- compendium/modules/w06-lab.tex
A first draft of the turtlegraphics lab.
> add draft for turtlegraphics lab

- compendium/modules/w13-assignment-imageprocessing.tex
Draft for imageprocessing assignment
> added draft for imageprocessing assignment

- modules/w04-lab.tex
Added skeleton for the pirate lab.
> Pirates labben.

- compendium/modules/w11-lab.tex
Specifications now properly use \begin{JavaSpec} instead of \begin{Code}.
Added some tips and extra(non-compulsory) lab assignments
> add further lab description and changed specifications

- compendium/modules/w09-lab.tex
Update lab description, change instructions for last task, add description of algorithm for last task
> Update description and instructions for lab9

- compendium/modules/w12-lab.tex
Here are some comments on the lab.
> Add: life comments

- compendium/modules/w05-lab.tex
Fix: pink-washing — changed “man” to neutral forms. Changed goals to "Kunna ...".
> Fix: Textual changes, pink-washing

- compendium/modules/w13-assignment-bank.tex
Added examples, changed to proper ScalaSpecification, changed comments to english, extended instructions, added extra tasks and made other various minor changes.
> First version of project bank

- compendium/modules/w11-lab.tex
Updated description to a second draft.
> Added lab description for lthopoly with new skeleton

- compendium/modules/w13-assignment-imageprocessing.tex
Instructions are now ready for testing!
> Improved the instructions for w13-assignment-imageprocessing

- compendium/modules/w04-lab.tex
Fix: added subtask to save file plus changed code för reading words.
> Add: subtask to save to file + code change

- compendium/modules/w06-lab.tex
I've added the static constants in SimpleWindow to the spec given in turtlegraphics.
Also added figure environments around the images in the lab with the following labels. Is this the appropriate naming style? Is "classes" the correct chapter name?
`\label{fig:classes:turtlegraphics:rectanglesequence}`
> Updates to turtlegraphics lab description

- compendium/modules/w04-lab.tex
> Fixed typo in w04-lab

- compendium/modules/w13-assignment-bank.tex
Fixed w13-assignment-bank instruction after having recieved input from test.
> w13-assignment-bank after test input

- compendium/modules/w08-lab.tex
> Corrected typos in w08 lab

- compendium/modules/w03-solutions.tex
Here is the first draft for the solutions to w03
> add w03-solutions all tasks done

- compendium/modules/w13-assignment-imageprocessing.tex
Updated small stuff in w13-assignment-imgprocessing
> Updated w13-assignment-imgprocessing

- compendium/modules/w04-lab.tex
incorporated feedback, major changes.
> Fixed pirates lab from testfeedback

- workspace/w04_pirates/src/main/scala/pirates/PirateSpeech.scala
- workspace/w04_pirates/src/main/scala/pirates/SaveCrew.scala
> Updated code skeletons for pirates

- compendium/modules/w08-exercise.tex
Solutions to basic exercises removed from w08-exercises.tex
> w08-exercises, solution removal

- compendium/modules/w10-exercise.tex
- compendium/modules/w10-solutions.tex
Added TASK headers and solutions. Also corrected minor errors. This PR does NOT contain any PDFs....hopefully.
> Updated w10 exercise and solution

- compendium/modules/w02-solutions.tex
Added solutions for basic exercises.
> Added solutions 2

- compendium/modules/w02-solutions.tex
Added spacing in order to fit everything onto the paper.
> Solutions + Fixed layout

- compendium/modules/w01-exercise.tex
- compendium/modules/w01-lab.tex
Fixed some typos and an inconsistency in task 14 (expressions)
> W01 exercises & lab (Typos & inconsistency)

- contributors.tex
I have tested the w08-lab and I have worked as a DEV for the w07-lab. Furthermore I have proofread several of the texts (labs & exercises) and fixed all of the typos/inconsistencies that I could find in these texts.
> Added myself to the list of contributors

- quickref/quickref.tex
- slides/body/lect-week01-intro.tex
> fix wrong error range of Int, is 2^31 (not 15)

- compendium/modules/w01-solutions.tex
Skrivet dubbla `for` facit på uppgift 23
> Dubbla "for"

- compendium/modules/w03-exercise.tex
- compendium/modules/w03-lab.tex
Chapter 3, page 69 (assignment 3 & 4)
Chapter 3, page 80, 83 & 84
> Fixed a few typos in w03-lab and w03-exercises

- compendium/modules/w04-solutions.tex
> Added solutions for w04

- compendium/modules/w05-solutions.tex
Currently the method is creating an Array with one element (= n+1), since it´s supposed to create an empty array with 4 elements: it should be `new Array[Int](n+1)` instead
> Wrong answer - Exercise 5.3a

- compendium/modules/w07-lab.tex
- compendium/modules/w11-lab.tex
Errata
Lab07-TurtleRace
- Clarified what the x-parameter for printTitle does
- Clarified the purpose of the Title String of simpleWindow
- Clarified how the 32 turtles are supposed to race in the TurtleTournament task.
Lab11-lthopoly
- Fixed several typos and grammatically incorrect wording
> fix task clarification and typos

- compendium/modules/w05-solutions.tex
val ys = Array[Int](n) Fills the Array with one 4
val ys = Array.fill[Int](n)(0) Fills the Array with four 0's which is wanted in this task.
> Changed Array to fill with 4 zeros

- compendium/modules/w11-exercise.tex
Fixes #222 and an issue that doesn't have an associated issue report.
> Fix compilation errors in search/sort chapter exercises

- compendium/modules/w12-lab.tex
Clarified actions, getAction, getPossibleActions
> update lab w12 description. Changed incorrect names of methods. 

- compendium/examples/lth-courses/courses.scala
- compendium/modules/w03-lab.tex
- compendium/modules/w04-exercise.tex
- compendium/modules/w04-lab.tex
- compendium/modules/w05-exercise.tex
- compendium/modules/w05-lab.tex
- compendium/modules/w06-exercise.tex
- compendium/modules/w07-exercise-goals.tex
- compendium/modules/w07-exercise.tex
- compendium/modules/w09-lab.tex
- compendium/modules/w10-exercise.tex
- compendium/modules/w11-exercise.tex
- compendium/modules/w12-exercise.tex
- compendium/modules/w13-exercise.tex
`lthopoly` and the projects (including `life`) will be handled in separate PRs.
> Fix small errors in compendium

- compendium/modules/w12-lab.tex
Same problem as with #218 and #220.
> lthopoly: Improve path handling

- compendium/modules/w12-lab.tex
- compendium/modules/w13-assignment-bank.tex
- compendium/modules/w13-assignment-imageprocessing.tex
- compendium/modules/w13-assignment-life.tex
- compendium/modules/w13-assignment-tictactoe.tex
- workspace/w13_bank_proj/src/main/scala/bank/BankEvent.scala
- workspace/w13_tictactoe_proj/src/main/scala/tictactoe/Game.scala
- workspace/w13_tictactoe_proj/src/main/scala/tictactoe/HumanPlayer.scala
- workspace/w13_tictactoe_proj/src/main/scala/tictactoe/OptimalPlayer.scala
- workspace/w13_tictactoe_proj/src/main/scala/tictactoe/Player.scala
As noted in the description for PR #242, I was going to make a separate PR for the projects. This is that PR. 
(lthopoly was mainly handled in PR #244, but there are some changes to it in this PR too.)
> Projects text cleanup

- compendium/modules/w01-intro-exercise.tex
Changed order of the solutions for task 6a and 6b for W01. Issue #284
> Changing order of solutions, W01 - 6a and 6b

- slides/body/lect-w03-functions.tex
A for-loop seems more reasonable since we know the number of iterations beforehand
> Update of W03 custom control structure example

- compendium/modules/w13-assignment-bank.tex
This will hopefully make the project easier to understand. See the commit messages for details.
> bank: Remove State class and remove confusing usage of the word "state" (plus misc rewording)

- compendium/modules/w13-assignment-bank.tex
> bank: Use Long for customer IDs

- workspace/w08_maze/src/main/scala/maze/Main.scala
This PR is essentially the same as PR #218. It seems like that PR got undone when the maze lab was rewritten recently.
> Make maze file paths work with special characters

- compendium/modules/w13-assignment-bank.tex
The students will need to write code for deserializing BankEvents, and the BankEvent file can be a good place to put that, so I would like to point out that editing it is allowed. (Putting the code in another place is also allowed, though.)
> bank: Allow making changes to BankEvent and Date

- compendium/modules/w13-assignment-bank.tex
> bank: Clean up the examples

- workspace/w13_bank_proj/src/main/scala/bank/BankEvent.scala
- workspace/w13_bank_proj/src/main/scala/bank/time/Date.scala
As suggested in https://github.com/lunduniversity/introprog/pull/314#pullrequestreview-69519421
> bank: Use scala.util.Try instead of try

- workspace/w13_bank_proj/src/main/scala/bank/BankEvent.scala
- workspace/w13_bank_proj/src/main/scala/bank/time/Date.scala
> bank: Make recover cases easier to read

- workspace/w10_music/src/main/scala/music/Synth.scala
Removed unnecessary code due to the merge of two different solutions for the same problem (#332 and #333)
> Remove unnecessary code in Synth.scala music lab

- README.md
- compendium/assignments.tex
- compendium/compendium.tex
- compendium/compendium1.tex
- compendium/compendium2.tex
- compendium/cover/cover-A3-part2.tex
- compendium/cover/cover-A3.tex
- compendium/exercises.tex
- compendium/global-constants.tex
- compendium/labs.tex
- compendium/lectures.tex
- compendium/prechapters/licence-contributors.tex
- compendium/solutions.tex
- slides/all-lectures.tex
- slides/body/lect-preamble.tex
Also adding the LaTeX command \CurrentYear to make this easier to update in the future.
> Update the year where necessary

- compendium/modules/w04-objects-lab.tex
- compendium/postchapters/debug.tex
The exact change on line 133 of debug.tex, in case it doesn't highlight in the diff, is:
> Ofta ~~vet~~ känner man till vilka villkor som måste gälla
> Fix minor text mistakes

- compendium/modules/w04-objects-lab.tex
- contributors.tex
Should probably be squashed on merge, I messed up the commits a bit.
> Blockmole example code: fix string interpolator

- compendium/modules/w11-scalajava-exercise.tex
Correct method name to match code.
> findAll -> foundAll

- compendium/modules/w04-objects-exercise.tex
The changes where made in the week for objects. There are still a need to make "introprog-X.Y.Z.jar"  clearer, i.e versions and such. The relevant pages for this is 121-122, 125-128, 133
> Removed SimpleWindow and other relics from earlier iteration

- slides/body/lect-w06-matching.tex
Signed-off-by: Jakob Sinclair <sinclair.jakob@mailbox.org>
> Fix some typos in w06-slides

- compendium/modules/w06-patterns-lab.tex
Just for those who are curious.
> blockbattle: Add a footnote about double buffering

- workspace/w11_javatext/src/main/java/game/Game.java
See https://github.com/lunduniversity/introprog/issues/429#issuecomment-558107682
> javatext: Remove getElapsedTimeMs from specification

- compendium/modules/w09-setmap-lab.tex
> Reword 9.3.3.4 fixing issue #430

- compendium/modules/w13-assignment-bank.tex
> Fix syntax

- compendium/modules/w08-matrices-lab.tex
- slides/body/lect-w04-objects.tex
> Fix implied typos

- compendium/modules/w08-matrices-lab.tex
- slides/body/lect-w04-objects.tex
over-populated or over populated are two words in English!?
> Revert "Fix implied typos"

- slides/body/lect-w06-option.tex
I think i found the simplest solution and something that would still make people remember the example. You can always ask the class about what is missing and see if they figure it out. The example of gender as a binary thing is a flawed way to describe human expression, behaviour and interaction.
> Adding three dots

- compendium/modules/w06-patterns-exercise.tex
Fixes issue #493 removes the excessive space before kanskePang on line 7.
> Fix #493 removed excessive space in chapter 6.2.1 assignment 10

- compendium/modules/w06-patterns-exercise.tex
Fix #495 the missing val is now added and this code compiles properly.
> Fix #495 added the missing val in Chapter 6.2.2

- slides/body/lect-w12-project-assignment.tex
I especially don't want students to get confused by the link http://cs.lth.se/pgk/sam which contains data from 2019.
> Update w12 slides for 2020

- compendium/modules/w12-sorting-exercise.tex
Added the missing quotaion mark in chapter L.12.1 assignment 2.
> Typo in chapter L.12.1 fixed

- workspace/w11_javatext/src/main/java/game/Main.java
`System.out` automatically flushes when a newline is printed, but we can't rely on automatic flushing when not printing a newline.
> javatext: Flush System.out after print

- compendium/modules/w13-assignment-imageprocessing.tex
PixelWindow is not an appropriate replacement for SimpleWindow for this project since it has no convenient way to display an image. (And this project requires cslib for other reasons anyway.)
> imageprocessing: Partially revert 99bdc34

- compendium/generated/quiz-w07-abstract-collections-solurows-generated.tex
- compendium/generated/quiz-w07-abstract-collections-taskrows-generated.tex
- compendium/modules/w07-sequences-exercise.tex
- quiz/QuizData.scala
Fixes #497. But unfortunately this makes the "mutant task" be task 4 instead of task 5 :(
> Remove exercise 7 task 3 (abstract collections quiz)

- .github/workflows/main.yml
- README.md
Added basic structure to support GitHub Actions, including a config file located in `.github/workflows/`. Edited `README.md` to properly display build status.
> added structure to support GH actions, fix #526

- compendium/modules/w04-objects-exercise.tex
Still have to test some parts in WSL 2 (WSL 1 doesn't play nice with AWT) and double check that I haven't missed anything, then this should be ready for merge.
> WIP: fix #558 by migrating w04 exercise to Scala 3

- web/tools/tools.md
Quick typo fix. I didn't update the html file with `build.sh` as the output file had some other unexpected changes.
> web/tools: Fix typo

- compendium/modules/w04-objects-lab.tex
do while is deprecated as of scala 3, this part shoudl therefore be removed
> removing deprecated part

- compendium/modules/w04-objects-lab.tex
https://dotty.epfl.ch/docs/reference/dropped-features/do-while.html
> scala 3 Do-While

- compendium/modules/w03-functions-lab.tex
- slides/body/lect-w03-functions.tex
* Fixed a couple of typos in lab preparations
> Fix chapter 3 typos

- compendium/modules/w10-inheritance-exercise.tex
Removed a second addition test identical to the first.
> Removed duplicate code from example

- compendium/modules/w03-functions-lab.tex
Ett förslag på tips för att komma igång, något omformulerat från det initiala förslaget.
Är något kluven till "Börja enkelt" förslaget, det kan få en effekt som vi inte önskar?
> irritext suggestions for how to start #479

- compendium/modules/w01-intro-exercise.tex
Fixed a small typo in exercise 35 in chapter 1.
> Fixed small typo

- slides/body/lect-w06-matching.tex
added `s` to make a string into a string polarization on line 197
> corrected a typo

- .github/workflows/main.yml
- Improve readability
- Add functionality to manually trigger workflow
- Rename job
- Run on two latest Ubuntu LTS
- Boilerplate for uploading PDF artifacts generated by build
> update workflow file

- compendium/modules/w02-programs-exercise.tex
> Update excercise 2.4 a)

- compendium/modules/w02-programs-exercise.tex
> Typo in compendium/modules/w02-programs-exercise.tex

- compendium/modules/w04-objects-lab.tex
Fix typo and migrate from scala-cli to scala (in this text section). Latex compiles.
> Edit small text section in `blockmole`

- compendium/modules/w06-patterns-exercise.tex
begynnelsbokstäver -> begynnelsebokstäver
> Fix spelling mistake in patterns exercise

- compendium/modules/w01-intro-exercise.tex
Körtiddsfel -> Körtidsfel
aritmetik aritmetik -> aritmetik
> fix typos in w01-intro-exercise

- slides/body/lect-w06-exceptions.tex
> Fix typo in sheet heading

- slides/body/lect-w07-enums.tex
> Fix typo in w07-enums

- .gitignore
- workspace/.gitignore
- workspace/w10_snake/.gitignore
> fix gitignore inline comments

- web/tools/tools.html
- web/tools/tools.md
Added instructions for installing git, and git bash as terminal alternative for Windows
> Git and Git Bash in tools.md

- web/tools/sound_in_wsl2.md
Add a guide to help people get sound working in WSL2.
> Add instructions about sound in WSL2

- web/tools/tools.md
Added instructions for ARM devices to install Scala tools.
> Update Scala installation instructions for ARM devices
